apiVersion: v2
name: poe-accountant
description: A Helm chart for poe-accountant platform with multi-service ingress routing
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: ingress-nginx
    version: 4.10.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
